clone_depth: 50

platform:
    - x86

configuration:
    # - Debug
    - Release
    # - RelWithDebInfo

install:
    - git submodule update --init --recursive
    - set PATH=C:\msys64\mingw32\bin;C:\msys64\usr\bin;%PATH%
    - pacman --noconfirm -Syuu --needed
    - pacman --noconfirm -S mingw-w64-i686-toolchain
    # - pacman --noconfirm -S mingw-w64-i686-cmake
    - pacman --noconfirm -S mingw-w64-i686-drmingw
    - pacman --noconfirm -S mingw-w64-i686-boost
    - pacman --noconfirm -S mingw-w64-i686-libxml2
    - pacman --noconfirm -S --force mingw-w64-i686-qt5

before_build:
    - md install
    - md build

build_script:
    - where cmake
    - where make
    - cd build
    - cmake .. -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DWITH_JEMALLOC=OFF -DBUILD_TESTING=ON -DCMAKE_VERBOSE_MAKEFILE=ON
    - make install/strip -j 2
    - cd ..

after_build:
    - set PATH=%PATH%;%CD%\install\bin

test_script:
    - catchsegv scram_tests
    - catchsegv scram --version
    - catchsegv scram input\TwoTrain\two_train.xml
    - cd build
    - ctest --verbose
    - cd ..

after_test:
    - cd build
    - cmake .. -DPACKAGE=ON
    - cpack --verbose
    - dir
    - cd ..

on_failure:
    - type build\_CPack_Packages\win32\NSIS\NSISOutput.log

artifacts:
    - path: build/SCRAM*.exe
      name: installer
