clone_depth: 50

platform:
    - x64

branches:
    except:
        - l10n_develop

configuration:
    # - Debug
    # - Release
    - RelWithDebInfo

install:
    - git submodule update --init --recursive
    - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S mingw-w64-x86_64-jemalloc
    - pacman --noconfirm -S mingw-w64-x86_64-boost
    - pacman --noconfirm -S mingw-w64-x86_64-libxml2
    - pacman --noconfirm -S mingw-w64-x86_64-qt5

before_build:
    - md install
    - md build

build_script:
    - cd build
    - cmake .. -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_CXX_FLAGS="-O3" -DCMAKE_VERBOSE_MAKEFILE=ON
    - make install/strip -j 2
    - cmake .. -DPACKAGE=ON
    - make install/strip -j 2
    - cpack --verbose
    - dir
    - cd ..

after_build:
    - set PATH=%PATH%;%CD%\install\bin

test_script:
    - scram_tests
    - scram --version
    - scram input\TwoTrain\two_train.xml

on_failure:
    - type build\_CPack_Packages\win64\NSIS\NSISOutput.log

artifacts:
    - path: build/SCRAM*.exe
      name: installer
